services:
  app:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
#    environment:
#      - PHP_ENABLE_XDEBUG=1
    ports:
      - '8000:80'
